apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-app-api-config
data:
  DB_HOST: your-db-service-name
  DB_PORT: "3306"
  DB_USER: root
  DB_NAME: hr_app
  HR_APP_ACCESS_TOKEN_MINUTES: "30"
  HR_APP_REFRESH_TOKEN_DAYS: "7"
